name: soccerapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  shared_preferences: ^2.0.15
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/노팅엄.png
    - assets/images/뉴캐슬.png
    - assets/images/레스터 시티 FC.png
    - assets/images/리버풀.png
    - assets/images/맨시티.png
    - assets/images/맨유.png
    - assets/images/본머스.png
    - assets/images/브라이튼.png
    - assets/images/브렌트포드.png
    - assets/images/사우샘프턴.png
    - assets/images/아스널.png
    - assets/images/애스턴 빌라.png
    - assets/images/에버턴.png
    - assets/images/울버햄튼.png
    - assets/images/웨스트햄.png
    - assets/images/입스위치 타운.png
    - assets/images/첼시.png
    - assets/images/크리스탈 팰리스.png
    - assets/images/토트넘.png
    - assets/images/풀럼.png

  fonts:
    - family: GmarketBold
      fonts:
        - asset: assets/fonts/GmarketSansTTFBold.ttf
    - family: GmarketLight
      fonts:
        - asset: assets/fonts/GmarketSansTTFLight.ttf
    - family: GmarketMedium
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf