// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_58X1rQQT9OCYrKNckvRHjNuK3Xl6gPE',
    appId: '1:1058561414036:android:e8a7a7f71a17332020b581',
    messagingSenderId: '1058561414036',
    projectId: 'kickoffbe',
    storageBucket: 'kickoffbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSwwnlL1gOlmlDyT7VVdu5bBamVOAxmWY',
    appId: '1:1058561414036:ios:b6e78dbd96d2e0bd20b581',
    messagingSenderId: '1058561414036',
    projectId: 'kickoffbe',
    storageBucket: 'kickoffbe.firebasestorage.app',
    iosBundleId: 'com.example.soccerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSwwnlL1gOlmlDyT7VVdu5bBamVOAxmWY',
    appId: '1:1058561414036:ios:b6e78dbd96d2e0bd20b581',
    messagingSenderId: '1058561414036',
    projectId: 'kickoffbe',
    storageBucket: 'kickoffbe.firebasestorage.app',
    iosBundleId: 'com.example.soccerapp',
  );
}
